# Generated by Django 3.2.8 on 2021-10-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images/slider/')),
                ('sira_no', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2)),
                ('durum', models.CharField(choices=[('True', 'Aktif'), ('False', 'Pasif')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('href', models.CharField(blank=True, max_length=150)),
                ('durum', models.CharField(choices=[('True', 'Aktif'), ('False', 'Pasif')], max_length=10)),
                ('sira_no', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
            ],
        ),
    ]
