# Generated by Django 3.2.8 on 2021-10-07 02:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('icerik', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('konum', models.CharField(choices=[('left', 'Sol'), ('right', 'Sağ')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='images/hakkimizda/')),
                ('sira_no', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('durum', models.CharField(choices=[('True', 'Aktif'), ('False', 'Pasif')], max_length=10)),
            ],
        ),
    ]
